// Endpoint Readiness Scanner v1.0.0. Native .NET Framework Windows Forms application.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Management;
using System.ServiceProcess;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Win32;

namespace EndpointReadinessScanner {
  public class Rule { public string Name {get;set;} public string ServiceName {get;set;} public bool Required {get;set;} public string MinimumVersion {get;set;} }
  public class AdminRule { public List<string> AllowedMembers {get;set;} }
  public class BitLockerRule { public bool Required {get;set;} public int MinimumEncryptionPercentage {get;set;} public bool RequireProtection {get;set;} }
  public class WindowsRule { public string Edition {get;set;} public string MinimumBuild {get;set;} public int MinimumUBR {get;set;} public List<string> ApprovedKB {get;set;} }
  public class Baseline { public string BaselineVersion {get;set;} public AdminRule LocalAdministrators {get;set;} public BitLockerRule BitLocker {get;set;} public List<Rule> SecurityAgents {get;set;} public List<Rule> RequiredSoftware {get;set;} public WindowsRule Windows {get;set;} }
  public class Device { public string Hostname, User, Domain, Manufacturer, Model, Serial, Windows, Version, Build; public int UBR; }
  public class ScanResult { public string Name {get;set;} public bool Critical {get;set;} public string Status {get;set;} public string Expected {get;set;} public string Detected {get;set;} public string Problem {get;set;} public string Action {get;set;} public string Icon { get { return Status=="OK" ? "✓" : Status=="FALLA" ? "✕" : Status=="ADVERTENCIA" ? "!" : "?"; } } }
  public class RoundedPanel : Panel { public int CornerRadius=12; public Color BorderColor=Color.FromArgb(220,228,238); public RoundedPanel(){DoubleBuffered=true;Padding=new Padding(1);} protected override void OnResize(EventArgs e){base.OnResize(e); if(Width>1&&Height>1)using(var p=PathFor(new Rectangle(0,0,Width-1,Height-1),CornerRadius))Region=new Region(p);} protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.SmoothingMode=SmoothingMode.AntiAlias; using(var path=PathFor(new Rectangle(0,0,Width-1,Height-1),CornerRadius))using(var brush=new SolidBrush(BackColor)){e.Graphics.FillPath(brush,path);}} protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var path=PathFor(new Rectangle(0,0,Width-1,Height-1),CornerRadius))using(var pen=new Pen(BorderColor)){e.Graphics.DrawPath(pen,path);}} static GraphicsPath PathFor(Rectangle box,int r){var p=new GraphicsPath();r=Math.Min(r,Math.Min(box.Width,box.Height)/2);p.AddArc(box.Left,box.Top,r*2,r*2,180,90);p.AddArc(box.Right-r*2,box.Top,r*2,r*2,270,90);p.AddArc(box.Right-r*2,box.Bottom-r*2,r*2,r*2,0,90);p.AddArc(box.Left,box.Bottom-r*2,r*2,r*2,90,90);p.CloseFigure();return p;} }
  public class RoundedButton : Button { public int CornerRadius=8; public RoundedButton(){FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;BackColor=Color.FromArgb(31,111,235);ForeColor=Color.White;DoubleBuffered=true;} protected override void OnResize(EventArgs e){base.OnResize(e);if(Width>1&&Height>1)using(var p=Path())Region=new Region(p);} protected override void OnPaintBackground(PaintEventArgs e){} protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=SmoothingMode.AntiAlias;using(var p=Path()){using(var b=new SolidBrush(Enabled?BackColor:Color.FromArgb(225,230,238)))e.Graphics.FillPath(b,p);} TextRenderer.DrawText(e.Graphics,Text,Font,ClientRectangle,Enabled?ForeColor:Color.DimGray,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);} GraphicsPath Path(){var r=new Rectangle(0,0,Width-1,Height-1);int c=Math.Min(CornerRadius,Math.Min(r.Width,r.Height)/2);var p=new GraphicsPath();p.AddArc(r.Left,r.Top,c*2,c*2,180,90);p.AddArc(r.Right-c*2,r.Top,c*2,c*2,270,90);p.AddArc(r.Right-c*2,r.Bottom-c*2,c*2,c*2,0,90);p.AddArc(r.Left,r.Bottom-c*2,c*2,c*2,90,90);p.CloseFigure();return p;} }

  static class Program {
    [STAThread] static void Main() { try { Application.EnableVisualStyles(); Application.SetCompatibleTextRenderingDefault(false); Application.Run(new ScannerForm()); } catch(Exception ex) { try { File.AppendAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Logs","StartupErrors.log"),DateTime.Now.ToString("s")+" "+ex+Environment.NewLine); } catch {} MessageBox.Show("No se pudo iniciar Endpoint Readiness Scanner. Revise Logs\\StartupErrors.log.\r\n\r\n"+ex.Message,"Error de inicio",MessageBoxButtons.OK,MessageBoxIcon.Error); } }
  }
  public class ScannerForm : Form {
    const string Version="1.0.0"; string root, evidenceFolder; Device device; Baseline baseline; DateTime started;
    readonly FlowLayoutPanel grid=new FlowLayoutPanel(); readonly TextBox details=new TextBox(); readonly ProgressBar progress=new ProgressBar(); readonly Label progressText=new Label(); readonly Label finalLabel=new Label(); readonly Panel info=new Panel(); readonly Label deviceHost=new Label(),deviceUser=new Label(),deviceSerial=new Label(),deviceModel=new Label(),deviceWindows=new Label(),deviceBuild=new Label(); readonly Button scan=new RoundedButton(), evidence=new RoundedButton(); readonly List<ScanResult> results=new List<ScanResult>(); readonly SplitContainer body=new SplitContainer(); readonly Panel bottom=new Panel(); int selectedIndex=-1;
    public ScannerForm() {
      root=Path.GetDirectoryName(Application.ExecutablePath); Text="Endpoint Readiness Scanner"; Size=new Size(1050,720); MinimumSize=new Size(860,590); StartPosition=FormStartPosition.CenterScreen; BackColor=Color.FromArgb(245,247,250); Font=new Font("Segoe UI",9); AutoScaleMode=AutoScaleMode.Dpi;
      var header=new Panel{Dock=DockStyle.Top,Height=87,BackColor=Color.FromArgb(23,54,93),Padding=new Padding(22,15,22,10)}; var productName=new Label{Text="Endpoint Readiness Scanner",ForeColor=Color.White,Font=new Font("Segoe UI",22,FontStyle.Bold),AutoSize=true,Location=new Point(20,12)}; var subtitle=new Label{Text="Preparación y validación de equipos Windows",ForeColor=Color.FromArgb(220,231,245),AutoSize=true,Location=new Point(23,52)}; var versionLabel=new Label{Text="Versión "+Version,ForeColor=Color.White,AutoSize=true}; header.Controls.Add(productName); header.Controls.Add(subtitle); header.Controls.Add(versionLabel); header.Resize+=(s,e)=>versionLabel.Location=new Point(Math.Max(20,header.ClientSize.Width-versionLabel.Width-22),20); Controls.Add(header);
      info.Dock=DockStyle.Top; info.Height=100; info.Padding=new Padding(22,10,22,8); info.BackColor=Color.White; AddInfoItem("EQUIPO",deviceHost,0,0); AddInfoItem("USUARIO",deviceUser,1,0); AddInfoItem("SERIAL",deviceSerial,2,0); AddInfoItem("MODELO",deviceModel,0,1); AddInfoItem("WINDOWS",deviceWindows,1,1); AddInfoItem("BUILD",deviceBuild,2,1); Controls.Add(info);
      body.Dock=DockStyle.Fill; body.SplitterDistance=600; body.Padding=new Padding(14,12,14,6); Controls.Add(body);
      var resultsPanel=new RoundedPanel{Dock=DockStyle.Fill,BackColor=Color.White,CornerRadius=14}; var tableHeader=new Panel{Height=36,BackColor=Color.FromArgb(235,241,248)}; tableHeader.Controls.Add(new Label{Text="  ESTADO",Location=new Point(8,10),AutoSize=true,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=Color.FromArgb(23,54,93)}); tableHeader.Controls.Add(new Label{Text="CONTROL",Location=new Point(82,10),AutoSize=true,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=Color.FromArgb(23,54,93)}); tableHeader.Controls.Add(new Label{Text="RESULTADO",Location=new Point(292,10),AutoSize=true,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=Color.FromArgb(23,54,93)}); grid.FlowDirection=FlowDirection.TopDown; grid.WrapContents=false; grid.AutoScroll=true; grid.Padding=new Padding(8,8,8,8); grid.BackColor=Color.White; resultsPanel.Resize+=(s,e)=>{tableHeader.Bounds=new Rectangle(1,1,resultsPanel.ClientSize.Width-2,36);grid.Bounds=new Rectangle(1,37,resultsPanel.ClientSize.Width-2,Math.Max(0,resultsPanel.ClientSize.Height-38));}; resultsPanel.Controls.Add(tableHeader); resultsPanel.Controls.Add(grid); body.Panel1.Controls.Add(resultsPanel);
      var detailsPanel=new RoundedPanel{Dock=DockStyle.Fill,BackColor=Color.White,CornerRadius=14}; details.Dock=DockStyle.Fill; details.Multiline=true; details.ReadOnly=true; details.ScrollBars=ScrollBars.Vertical; details.BorderStyle=BorderStyle.None; details.BackColor=Color.White; details.Font=new Font("Segoe UI",10); details.Padding=new Padding(14); detailsPanel.Controls.Add(details); detailsPanel.Controls.Add(new Label{Text="DETALLE DEL CONTROL SELECCIONADO",Dock=DockStyle.Top,Height=34,Padding=new Padding(12,9,0,0),Font=new Font("Segoe UI",9,FontStyle.Bold),ForeColor=Color.FromArgb(23,54,93),BackColor=Color.White}); body.Panel2.Controls.Add(detailsPanel);
      bottom.Dock=DockStyle.Bottom; bottom.Height=118; bottom.Padding=new Padding(20,8,20,9); bottom.BackColor=Color.White; progressText.AutoSize=true; progressText.Location=new Point(20,8); progressText.Text="Listo para iniciar la validación."; bottom.Controls.Add(progressText); progress.Location=new Point(20,30); progress.Width=990; progress.Height=15; progress.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top; bottom.Controls.Add(progress); finalLabel.AutoSize=true; finalLabel.Font=new Font("Segoe UI",14,FontStyle.Bold); finalLabel.Text="PENDIENTE DE VALIDACIÓN"; finalLabel.Location=new Point(20,56); bottom.Controls.Add(finalLabel);
      var actions=new FlowLayoutPanel{Width=350,Height=40,FlowDirection=FlowDirection.LeftToRight,WrapContents=false,Padding=new Padding(0,2,0,0),BackColor=Color.White}; scan.Text="▶  INICIAR ESCANEO"; scan.Font=new Font("Segoe UI",9,FontStyle.Bold); scan.Size=new Size(178,31); scan.Margin=new Padding(3); scan.BackColor=Color.FromArgb(31,111,235); scan.Click+=async(s,e)=>await RunScan(); actions.Controls.Add(scan); evidence.Text="ABRIR EVIDENCIA"; evidence.Size=new Size(150,31); evidence.Margin=new Padding(3); evidence.BackColor=Color.FromArgb(235,244,255); evidence.ForeColor=Color.FromArgb(20,82,160); evidence.Enabled=false; evidence.Click+=(s,e)=>{if(Directory.Exists(evidenceFolder)) Process.Start("explorer.exe",evidenceFolder);}; actions.Controls.Add(evidence); bottom.Controls.Add(actions); bottom.Resize+=(s,e)=>actions.Location=new Point(Math.Max(20,bottom.ClientSize.Width-actions.Width-20),bottom.ClientSize.Height-actions.Height-12); actions.BringToFront(); Controls.Add(bottom);
      header.Dock=DockStyle.None; info.Dock=DockStyle.None; body.Dock=DockStyle.None; bottom.Dock=DockStyle.None;
      Action arrangeLayout=()=>{int infoHeight=100, headerHeight=87, footerHeight=118; info.Bounds=new Rectangle(0,0,ClientSize.Width,infoHeight); header.Bounds=new Rectangle(0,infoHeight,ClientSize.Width,headerHeight); body.Bounds=new Rectangle(0,infoHeight+headerHeight,ClientSize.Width,Math.Max(120,ClientSize.Height-infoHeight-headerHeight-footerHeight)); bottom.Bounds=new Rectangle(0,ClientSize.Height-footerHeight,ClientSize.Width,footerHeight);};
      Resize+=(s,e)=>arrangeLayout(); Shown+=(s,e)=>arrangeLayout(); Load+=async(s,e)=>{arrangeLayout(); body.SplitterDistance=Math.Max(480,(body.ClientSize.Width*62)/100); InitializePendingResults(); await LoadDevice();};
    }
    void InitializePendingResults() { if(results.Count>0)return; foreach(string name in new[]{"Administradores locales","BitLocker","Agentes de seguridad","Software base","Windows / KB"})results.Add(Result(name,"NO EVALUADO","Presione INICIAR ESCANEO.","Pendiente de validación.","El control todavía no fue evaluado.","Inicie el escaneo para obtener el resultado.")); selectedIndex=0; Bind(); ShowDetails(); }
    void AddInfoItem(string caption,Label value,int column,int row){int x=22+column*315,y=9+row*39; info.Controls.Add(new Label{Text=caption,Location=new Point(x,y),AutoSize=true,Font=new Font("Segoe UI",7,FontStyle.Bold),ForeColor=Color.FromArgb(91,107,125)}); value.Location=new Point(x,y+14);value.Size=new Size(290,20);value.Font=new Font("Segoe UI",9,FontStyle.Bold);value.ForeColor=Color.FromArgb(23,54,93);value.AutoEllipsis=true;info.Controls.Add(value);}
    async Task LoadDevice() { try { device=await Task.Run(()=>GetDevice()); DisplayDevice(); } catch(Exception ex) { deviceHost.Text="No disponible"; deviceUser.Text="No disponible"; deviceSerial.Text="No disponible"; deviceModel.Text="Error: "+ex.Message; } }
    void DisplayDevice() { deviceHost.Text=device.Hostname; deviceUser.Text=device.User; deviceSerial.Text=device.Serial; deviceModel.Text=device.Manufacturer+" "+device.Model; deviceWindows.Text=device.Windows; deviceBuild.Text=device.Build+"."+device.UBR+" · "+device.Version; }
    async Task RunScan() {
      scan.Enabled=false; evidence.Enabled=false; try { progressText.Text="Eliminando evidencia temporal anterior..."; ClearPreviousEvidence(); results.Clear(); Bind(); progress.Value=0; started=DateTime.Now; SetFinal("VALIDANDO EQUIPO...",Color.DarkGoldenrod);
        string path=Path.Combine(root,"Baseline.json"); if(!File.Exists(path)) throw new Exception("No existe Baseline.json."); baseline=new JavaScriptSerializer().Deserialize<Baseline>(File.ReadAllText(path)); if(device==null) device=await Task.Run(()=>GetDevice());
        var checks=new Func<ScanResult>[] {()=>CheckAdmins(),()=>CheckBitLocker(),()=>CheckAgents(),()=>CheckSoftware(),()=>CheckWindows()};
        for(int i=0;i<checks.Length;i++) { progressText.Text="Validando control "+(i+1)+" de "+checks.Length+"..."; progress.Style=ProgressBarStyle.Marquee; progress.MarqueeAnimationSpeed=28; ScanResult r=await Task.Run(checks[i]); progress.Style=ProgressBarStyle.Continuous; progress.Value=(i+1)*20; results.Add(r); selectedIndex=results.Count-1; Bind(); ShowDetails(); }
        var failing=results.Where(r=>r.Critical && r.Status!="OK").ToList(); SetFinal(failing.Count==0?"APTO PARA ENTREGA":"NO APTO PARA ENTREGA", failing.Count==0?Color.FromArgb(22,101,52):Color.FromArgb(180,35,24)); progressText.Text="Validación terminada. La evidencia fue generada automáticamente."; CreateEvidence();
      } catch(Exception ex) { results.Add(Result("Baseline / inicialización","NO EVALUADO","Baseline.json válido","",ex.Message,"Revise Baseline.json y vuelva a ejecutar.")); Bind(); SetFinal("NO APTO PARA ENTREGA",Color.Firebrick); progressText.Text="Error de inicialización. Revise Logs\\Scanner.log."; Log("ERROR: "+ex); } finally { scan.Enabled=true; }
    }
    void Bind() { if(grid.IsDisposed)return; grid.SuspendLayout(); grid.Controls.Clear(); for(int index=0;index<results.Count;index++) {var r=results[index]; int capture=index; var row=new RoundedPanel{Width=Math.Max(360,grid.ClientSize.Width-28),Height=46,Margin=new Padding(0,0,0,7),BackColor=capture==selectedIndex?Color.FromArgb(235,244,255):Color.White,BorderColor=Color.FromArgb(215,225,238),CornerRadius=10,Cursor=Cursors.Hand}; Color color=r.Status=="OK"?Color.ForestGreen:r.Status=="FALLA"?Color.Firebrick:r.Status=="ADVERTENCIA"?Color.DarkGoldenrod:Color.DimGray; var icon=new Label{Text=r.Icon,Location=new Point(20,10),Width=26,Height=25,Font=new Font("Segoe UI",14,FontStyle.Bold),ForeColor=color,TextAlign=ContentAlignment.MiddleCenter}; var name=new Label{Text=r.Name,Location=new Point(75,14),Width=195,Height=22,Font=new Font("Segoe UI",9,FontStyle.Bold),ForeColor=Color.FromArgb(25,47,74)}; var status=new Label{Text=r.Status,Location=new Point(275,14),Width=100,Height=22,Font=new Font("Segoe UI",8,FontStyle.Bold),ForeColor=color}; var eye=new RoundedButton{Text="👁  VER",Location=new Point(Math.Max(370,row.Width-96),9),Size=new Size(86,28),Font=new Font("Segoe UI",8,FontStyle.Bold),BackColor=Color.FromArgb(225,238,255),ForeColor=Color.FromArgb(20,82,160)}; EventHandler select=(s,e)=>{selectedIndex=capture; Bind(); ShowDetails();}; row.Click+=select; icon.Click+=select; name.Click+=select; status.Click+=select; eye.Click+=select; row.Controls.Add(icon);row.Controls.Add(name);row.Controls.Add(status);row.Controls.Add(eye);grid.Controls.Add(row);} grid.ResumeLayout(); }
    void ShowDetails() { if(selectedIndex<0 || selectedIndex>=results.Count) return; var r=results[selectedIndex]; details.Text=r.Name+"\r\n\r\nEstado: "+r.Status+"\r\n\r\nEsperado:\r\n"+r.Expected+"\r\n\r\nDetectado:\r\n"+r.Detected+"\r\n\r\nProblema:\r\n"+r.Problem+"\r\n\r\nAcción recomendada:\r\n"+r.Action; }
    void SetFinal(string text,Color color) { finalLabel.Text=text; finalLabel.ForeColor=color; }
    ScanResult Result(string name,string status,string expected,string detected,string problem,string action) { return new ScanResult{Name=name,Critical=true,Status=status,Expected=expected,Detected=detected,Problem=problem,Action=action}; }
    Device GetDevice() { var d=new Device{Hostname=Environment.MachineName,User=Environment.UserDomainName+"\\"+Environment.UserName}; using(var s=new ManagementObjectSearcher("SELECT Manufacturer,Model,Domain FROM Win32_ComputerSystem")) foreach(ManagementObject o in s.Get()) {d.Manufacturer=""+o["Manufacturer"];d.Model=""+o["Model"];d.Domain=""+o["Domain"];break;} using(var s=new ManagementObjectSearcher("SELECT SerialNumber FROM Win32_BIOS")) foreach(ManagementObject o in s.Get()) {d.Serial=""+o["SerialNumber"];break;} using(var k=Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion")) {d.Windows=""+k.GetValue("ProductName");d.Version=""+k.GetValue("DisplayVersion");d.Build=""+k.GetValue("CurrentBuildNumber");int.TryParse(""+k.GetValue("UBR"),out d.UBR); int build; if(int.TryParse(d.Build,out build) && build>=22000 && d.Windows.StartsWith("Windows 10",StringComparison.OrdinalIgnoreCase)) d.Windows="Windows 11"+d.Windows.Substring("Windows 10".Length); } return d; }
    ScanResult CheckAdmins() {
      try {
        var allowed=baseline.LocalAdministrators==null?null:baseline.LocalAdministrators.AllowedMembers;
        string groupPath=null;
        using(var groups=new ManagementObjectSearcher("SELECT * FROM Win32_Group WHERE SID='S-1-5-32-544'"))
          foreach(ManagementObject g in groups.Get()){groupPath=g.Path.RelativePath;break;}
        if(string.IsNullOrWhiteSpace(groupPath))throw new Exception("No se encontró el grupo local con SID S-1-5-32-544.");
        var members=new List<string>();
        using(var s=new ManagementObjectSearcher("ASSOCIATORS OF {"+groupPath+"} WHERE AssocClass=Win32_GroupUser Role=GroupComponent"))
          foreach(ManagementObject o in s.Get())members.Add((o["Domain"]??"")+"\\"+(o["Name"]??""));
        List<string> localAdmins=new List<string>(), localUsers=new List<string>();
        using(var users=new ManagementObjectSearcher("SELECT Name,Disabled FROM Win32_UserAccount WHERE LocalAccount=True"))
          foreach(ManagementObject user in users.Get()){
            string account=Environment.MachineName+"\\"+user["Name"];
            string text="- "+account+(Convert.ToBoolean(user["Disabled"])?" (deshabilitado)":"");
            if(members.Contains(account,StringComparer.OrdinalIgnoreCase))localAdmins.Add(text); else localUsers.Add(text);
          }
        var detected=new List<string>{"CUENTAS LOCALES ADMINISTRADORAS:"};
        if(localAdmins.Any())detected.AddRange(localAdmins);else detected.Add("- Ninguna");
        detected.Add("");detected.Add("CUENTAS LOCALES SIN PRIVILEGIOS ADMINISTRATIVOS:");
        if(localUsers.Any())detected.AddRange(localUsers);else detected.Add("- Ninguna");
        var nonLocalAdmins=members.Where(m=>!m.StartsWith(Environment.MachineName+"\\",StringComparison.OrdinalIgnoreCase)).ToList();
        if(nonLocalAdmins.Any()){detected.Add("");detected.Add("MIEMBROS DE DOMINIO CON PRIVILEGIOS ADMINISTRATIVOS:");foreach(string member in nonLocalAdmins)detected.Add("- "+member);}
        string details=string.Join("\r\n",detected);
        if(allowed==null||allowed.Count==0)return Result("Administradores locales","ADVERTENCIA","Miembros autorizados definidos en Baseline.json",details,"No se puede comparar sin una lista autorizada.","Configure LocalAdministrators.AllowedMembers.");
        var bad=members.Where(m=>!allowed.Contains(m,StringComparer.OrdinalIgnoreCase)).ToList();
        return bad.Count>0?Result("Administradores locales","FALLA","Solo: "+string.Join(", ",allowed),details,"Miembros no autorizados: "+string.Join(", ",bad),"Retire los miembros no autorizados y revalide."):Result("Administradores locales","OK","Solo: "+string.Join(", ",allowed),details,"","");
      } catch(Exception e) {return Result("Administradores locales","NO EVALUADO","Consultar grupo SID S-1-5-32-544","",e.Message,"Ejecute como administrador y revalide.");}
    }
    ScanResult CheckBitLocker() { try { var statuses=new List<string>(); int active=0,inactive=0,unknown=0; foreach(var drive in DriveInfo.GetDrives().Where(d=>d.DriveType==DriveType.Fixed&&d.IsReady)){ string output=RunRaw("manage-bde.exe","-status "+drive.Name.TrimEnd('\\')); bool isActive=Regex.IsMatch(output,@"Protection\s+On|Protecci.n\s+activad|Protecci.n\s+habilitad",RegexOptions.IgnoreCase); bool isInactive=Regex.IsMatch(output,@"Protection\s+Off|Protecci.n\s+desactivad|not BitLocker protected|no est. protegido por BitLocker|no est. cifrado con BitLocker",RegexOptions.IgnoreCase); if(isActive){statuses.Add(drive.Name+"  —  ACTIVO");active++;}else if(isInactive){statuses.Add(drive.Name+"  —  DESACTIVADO");inactive++;}else{var statusLine=Regex.Match(output,@"(?im)^\s*(?:Protection Status|Estado de protecci.n)\s*:\s*(.+)$");statuses.Add(drive.Name+"  —  NO EVALUADO"+(statusLine.Success?" ("+statusLine.Groups[1].Value.Trim()+")":""));unknown++;}} if(statuses.Count==0)return Result("BitLocker","NO EVALUADO","BitLocker activo en las unidades fijas.","No se encontraron unidades fijas.","No hay unidades para consultar.","Revise las unidades del equipo."); string detected=string.Join("\r\n",statuses); if(inactive==0&&unknown==0)return Result("BitLocker","OK","BitLocker activo en todas las unidades fijas.",detected,"",""); if(inactive>0)return Result("BitLocker","FALLA","BitLocker activo en todas las unidades fijas.",detected,"Hay una o más unidades sin BitLocker activo.","Active BitLocker en las unidades indicadas antes de entregar el equipo."); return Result("BitLocker","NO EVALUADO","BitLocker activo en las unidades fijas.",detected,"No se pudo obtener el estado de una o más unidades.","Revise los permisos administrativos y vuelva a validar."); } catch(Exception e){return Result("BitLocker","NO EVALUADO","BitLocker activo en las unidades fijas.","",e.Message,"Ejecute como administrador y vuelva a validar.");} }
    ScanResult CheckAgents() { var list=baseline.SecurityAgents??new List<Rule>(); if(!list.Any()) return Result("Agentes de seguridad","ADVERTENCIA","Agentes definidos en Baseline.json","No hay agentes configurados.","No se puede validar sin una lista.","Configure SecurityAgents."); var d=new List<string>();var p=new List<string>(); foreach(var r in list.Where(x=>x.Required)){try{var s=new ServiceController(r.ServiceName);var st=s.Status.ToString();d.Add(r.Name+": "+st);if(st!="Running")p.Add(r.Name+": servicio no ejecutándose");}catch{d.Add(r.Name+": no encontrado");p.Add(r.Name+": servicio no encontrado");}} return p.Any()?Result("Agentes de seguridad","FALLA","Servicios requeridos instalados y ejecutándose",string.Join("\r\n",d),string.Join("\r\n",p),"Instale o inicie los agentes y revalide."):Result("Agentes de seguridad","OK","Servicios requeridos instalados y ejecutándose",string.Join("\r\n",d),"",""); }
    ScanResult CheckSoftware() { var list=baseline.RequiredSoftware??new List<Rule>(); if(!list.Any())return Result("Software base","ADVERTENCIA","Software definido en Baseline.json","No hay software configurado.","No se puede validar sin una lista.","Configure RequiredSoftware."); var all=Installed();var d=new List<string>();var p=new List<string>();foreach(var r in list.Where(x=>x.Required)){var f=all.FirstOrDefault(x=>x.Item1.IndexOf(r.Name,StringComparison.OrdinalIgnoreCase)>=0);if(f==null){d.Add(r.Name+": no instalado");p.Add(r.Name+": no instalado");}else{d.Add(r.Name+": "+f.Item2);Version a,b;if(!string.IsNullOrWhiteSpace(r.MinimumVersion)&&(!System.Version.TryParse(f.Item2,out a)||!System.Version.TryParse(r.MinimumVersion,out b)||a<b))p.Add(r.Name+": versión inferior a "+r.MinimumVersion);}}return p.Any()?Result("Software base","FALLA","Software y versiones según baseline",string.Join("\r\n",d),string.Join("\r\n",p),"Instale o actualice el software y revalide."):Result("Software base","OK","Software y versiones según baseline",string.Join("\r\n",d),"",""); }
    List<Tuple<string,string>> Installed(){var x=new List<Tuple<string,string>>();foreach(var path in new[]{@"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall",@"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"})using(var k=Registry.LocalMachine.OpenSubKey(path)){if(k==null)continue;foreach(var n in k.GetSubKeyNames())using(var a=k.OpenSubKey(n)){var name=""+a.GetValue("DisplayName");if(!string.IsNullOrWhiteSpace(name))x.Add(Tuple.Create(name,""+a.GetValue("DisplayVersion")));}}return x;}
    ScanResult CheckWindows(){try{var w=baseline.Windows;if(w==null)return Result("Windows / KB","NO EVALUADO","Configuración Windows","","Falta la sección Windows.","Complete Baseline.json.");var issues=new List<string>();if(!string.IsNullOrWhiteSpace(w.Edition)&&device.Windows.IndexOf(w.Edition,StringComparison.OrdinalIgnoreCase)<0)issues.Add("Edición requerida: "+w.Edition);int mb;if(int.TryParse(w.MinimumBuild,out mb)&&int.Parse(device.Build)<mb)issues.Add("Build mínimo: "+mb);if(w.MinimumUBR>0&&device.UBR<w.MinimumUBR)issues.Add("UBR mínimo: "+w.MinimumUBR);var kb=new List<string>();using(var s=new ManagementObjectSearcher("SELECT HotFixID FROM Win32_QuickFixEngineering"))foreach(ManagementObject o in s.Get())kb.Add(""+o["HotFixID"]);foreach(var k in w.ApprovedKB??new List<string>())if(!kb.Contains(k,StringComparer.OrdinalIgnoreCase))issues.Add("KB faltante: "+k);string det="Edición: "+device.Windows+"\r\nBuild: "+device.Build+"."+device.UBR+"\r\nKB instaladas: "+string.Join(", ",kb);return issues.Any()?Result("Windows / KB","FALLA","Edición, build, UBR y KB según baseline",det,string.Join("\r\n",issues),"Instale las actualizaciones aprobadas y revalide."):Result("Windows / KB","OK","Edición, build, UBR y KB según baseline",det,"","");}catch(Exception e){return Result("Windows / KB","NO EVALUADO","Consultar Windows y KB","",e.Message,"Revise permisos y revalide.");}}
    static int MatchInt(string s,string p){var m=Regex.Match(s,p,RegexOptions.IgnoreCase);int n;return m.Success&&int.TryParse(m.Groups[1].Value,out n)?n:0;} static string Run(string file,string args){var p=Process.Start(new ProcessStartInfo(file,args){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true});string o=p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd();p.WaitForExit();if(p.ExitCode!=0)throw new Exception(o);return o;} static string RunRaw(string file,string args){var p=Process.Start(new ProcessStartInfo(file,args){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true});string o=p.StandardOutput.ReadToEnd()+p.StandardError.ReadToEnd();p.WaitForExit();return o;}
    void ClearPreviousEvidence(){string evidenceRoot=Path.Combine(root,"Evidence"); if(Directory.Exists(evidenceRoot))foreach(string item in Directory.GetFileSystemEntries(evidenceRoot)){if(Directory.Exists(item))Directory.Delete(item,true);else File.Delete(item);} Directory.CreateDirectory(evidenceRoot); evidenceFolder=null; Log("Previous temporary evidence removed.");}
    void CreateEvidence(){var now=DateTime.Now;string serial=Regex.Replace(device.Serial??"UNKNOWN",@"[^a-zA-Z0-9._-]","_");evidenceFolder=Path.Combine(root,"Evidence",now.ToString("yyyy"),now.ToString("MM"),serial+"_"+now.ToString("yyyyMMdd_HHmmss"));Directory.CreateDirectory(evidenceFolder);string final=results.All(x=>!x.Critical||x.Status=="OK")?"APTO PARA ENTREGA":"NO APTO PARA ENTREGA";var data=new {Scanner=new{Name="Endpoint Readiness Scanner",Version},BaselineVersion=baseline.BaselineVersion,Device=device,Execution=new{Date=started.ToString("yyyy-MM-dd"),Time=started.ToString("HH:mm:ss")},Results=results,FinalResult=final};File.WriteAllText(Path.Combine(evidenceFolder,"Resultado.json"),new JavaScriptSerializer().Serialize(data),Encoding.UTF8);File.WriteAllLines(Path.Combine(evidenceFolder,"Resumen.txt"),new[]{"Endpoint Readiness Scanner "+Version,"Equipo: "+device.Hostname,"Serial: "+device.Serial,"Usuario: "+device.User,"Resultado: "+final,""}.Concat(results.Select(r=>"["+r.Status+"] "+r.Name+" - "+r.Problem)),Encoding.UTF8);File.WriteAllText(Path.Combine(evidenceFolder,"Auditoria.log"),"Inicio: "+started.ToString("s")+"\r\nFin: "+DateTime.Now.ToString("s")+"\r\nResultado: "+final,Encoding.UTF8);evidence.Enabled=true;Log("Evidence created: "+evidenceFolder);}
    void Log(string text){Directory.CreateDirectory(Path.Combine(root,"Logs"));File.AppendAllText(Path.Combine(root,"Logs","Scanner.log"),DateTime.Now.ToString("s")+" "+text+Environment.NewLine);}
  }
}
